# Generated by Django 4.1.13 on 2024-11-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_users_nature_alter_users_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='nature',
        ),
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(default='Utilisateur', max_length=15),
        ),
    ]
